### ISSUE TITLE
Error installing in node-red

### ISSUE THREAD

**Issue by gorstj** [hufftheweevil/node-red-contrib-august#1]
Hi,

This palette fails to install in Node-Red with the following error in the log.

Any ideas? Other packages are installing without issue.

`2022-05-25T10:07:58.913Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-august@1.1.0
2022-05-25T10:07:59.364Z [err] npm
2022-05-25T10:07:59.364Z [err]  WARN
2022-05-25T10:07:59.364Z [err]  config production Use `--omit=dev` instead.
2022-05-25T10:08:01.060Z [out] 
2022-05-25T10:08:01.060Z [out] up to date in 2s
2022-05-25T10:08:01.071Z rc=0`

**Comment by gorstj** [comment]
Ok seems this error is just one of those things as it appear with other packages that do install.

When I install August it comes up with the attached error. The log entry is as above.
![error](https://user-images.githubusercontent.com/2826513/170243369-35d0eefd-97c0-424e-a8d3-891488408728.JPG)

Doesn't appear in the pallete as installed or in the nodes on the left side (after a restart too)

I have tried installing on the command line and it appears it is already installed. Just doesn't show up as installed in the palette

`john@kit:~/.node-red$ npm install node-red-contrib-august

up to date, audited 497 packages in 4s

20 packages are looking for funding
  run `npm fund` for details

11 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
`

**Comment by gorstj** [comment]
Apologies - I was running an old version of node-red (1.3) and this requires a version >2 

(I had to run node-red on the command line to figure out the error)

Is it possible for the node to declare the reason it doesn't install?

Closed from my perspective

**Comment by hufftheweevil** [comment]
It is specified in the `package.json`: https://github.com/hufftheweevil/node-red-contrib-august/blob/2ea97045e335031060755de162236cdbe7424186/package.json#L13

I appreciate your request - however this could be asked about every node. So I don't think the node is the right place for it to happen. I think Node-RED itself should give a clearer reason for the install fail.
